//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class apiUser
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public bool AdminCheck { get; set; }
    }
}
